spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration

external-api:
  stock:
    app-key: ${STOCK_API_APP_KEY:}
    app-secret: ${STOCK_API_APP_SECRET:}
    rest-base-url: ${STOCK_API_REST_BASE_URL:}
    websocket-url: ${STOCK_API_WEBSOCKET_URL:}